ALTER TABLE "Setting" ADD COLUMN "slaBusinessHours" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Setting" ADD COLUMN "slaWorkdayStart" INTEGER NOT NULL DEFAULT 9;
ALTER TABLE "Setting" ADD COLUMN "slaWorkdayEnd" INTEGER NOT NULL DEFAULT 18;
ALTER TABLE "Setting" ADD COLUMN "slaWorkDays" TEXT NOT NULL DEFAULT '1,2,3,4,5';
